name: build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Checkout repository and submodules
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pints>=0.3
        python -m pip install scipy>=1.7
        python -m pip install numpy>=1.21
        python -m pip install matplotlib>=3.4
        python -m pip install pandas>=1.3
        python -m pip install networkx>=2.6
        python -m pip install plotly>=5.3
        python -m pip install symengine>=0.8
        python -m pip install sympy>=1.8
        python -m pip install pygraphviz==1.7
    - name: Lint with flake8
      run: |
        python -m flake8
    - name: Test sorting wioth isort
      run: |
        python -m isort --verbose --check-only --diff markov_builder tests setup.py
    - name: Test with pytest
      run: |
        python -m pytest --cov --cov-config=.coveragerc
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
