name: build
on: [pull_request]

env:
  MARKOVBUILDER_TEST_OUTPUT: tmp/

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Lint with flake8
      run: |
        python -m flake8
    - name: Import sorting with isort
      run: |
        python -m isort --verbose --check-only --diff markov_builder tests setup.py
    - name: Test with pytest
      run: |
        python -m pytest --cov --cov-config=.coveragerc
    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
